package com.derycode.deryaccount.billing

import android.content.Context
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Locale
import javax.crypto.Mac
import javax.crypto.spec.SecretKeySpec

/**
 * DeryAccount subscription model.
 *
 * The app works fully offline, so there is no payment gateway wired into
 * it directly — a shop pays DeryCode (mobile money / bank), and DeryCode
 * (Wema/Derick) sends back an ACTIVATION CODE that is typed once into
 * Settings → Subscription. The code is self-verifying (HMAC-signed) so
 * it works with zero connectivity, forever, without phoning any server.
 *
 * New installs get a free trial with every feature unlocked so a shop
 * can try the full system before paying. When the trial ends without an
 * activation code, the app never locks the books — it quietly drops to
 * the STARTER feature set so a shop can always see and print its own
 * data; only the higher-tier conveniences are gated.
 */
enum class PlanTier(
    val code: String,             // 2-letter code used inside activation keys
    val displayName: String,
    val tagline: String,
    val monthlyUgx: Long,
    val foundingYearlyUgx: Long,  // "Founding 100" annual price (~17% off monthly*12)
    val maxUsers: Int,            // Int.MAX_VALUE = unlimited
    val maxBranches: Int,
    val popular: Boolean = false,
    val features: List<String>
) {
    STARTER(
        "ST", "Starter", "Small Shops & Startups",
        monthlyUgx = 10_000, foundingYearlyUgx = 100_000,
        maxUsers = 1, maxBranches = 1,
        features = listOf(
            "Sales / POS", "Inventory Management", "Customers & Suppliers",
            "Expenses", "Cash Book", "Basic Reports", "Receipts (Print / PDF)",
            "Offline Operation", "1 Business", "1 User"
        )
    ),
    BUSINESS(
        "BU", "Business", "Shops, Supermarkets, Wholesalers",
        monthlyUgx = 20_000, foundingYearlyUgx = 200_000,
        maxUsers = 5, maxBranches = 1, popular = true,
        features = listOf(
            "All Starter Features", "Multiple Users (Up to 5)", "Advanced Reports",
            "Debtors & Credit Sales", "Suppliers & Purchases",
            "Stock Adjustments & Transfers", "Profit & Loss, Balance Sheet",
            "Backup & Restore", "Priority Support"
        )
    ),
    PROFESSIONAL(
        "PR", "Professional", "Growing & Large Businesses",
        monthlyUgx = 35_000, foundingYearlyUgx = 350_000,
        maxUsers = 15, maxBranches = 1,
        features = listOf(
            "All Business Features", "Multiple Users (Up to 15)", "Advanced Permissions",
            "Audit Trail / Activity Log", "Multi-Currency Support",
            "Advanced Stock Valuation", "Tax / VAT Management",
            "Customer & Supplier Statements", "Cloud Sync & Automatic Backup",
            "Priority Support"
        )
    ),
    MULTI_BRANCH(
        "MB", "Multi-Branch", "Businesses with Branches",
        monthlyUgx = 60_000, foundingYearlyUgx = 600_000,
        maxUsers = Int.MAX_VALUE, maxBranches = Int.MAX_VALUE,
        features = listOf(
            "All Professional Features", "Multiple Branches", "Consolidated Reports",
            "Branch Stock Transfer", "User Roles (Advanced)", "Advanced Analytics Dashboard",
            "API Access (Coming Soon)", "Dedicated Account Manager", "Priority Support (24/7)"
        )
    );

    companion object {
        fun byCode(code: String): PlanTier? = values().find { it.code == code }
    }
}

data class LicenseState(
    val plan: PlanTier,
    val isTrial: Boolean,
    val trialDaysLeft: Int,
    val isLicensed: Boolean,     // has a currently-valid activation code
    val isExpired: Boolean,      // had a license/trial that ran out — floor to Starter
    val expiresAt: Long?,        // epoch millis, null = trial or no expiry recorded
    val licenseKey: String?
) {
    /** The plan whose feature set actually applies right now. */
    val effectivePlan: PlanTier get() = if (isTrial || isLicensed) plan else PlanTier.STARTER
}

/** Offline-verifiable activation codes: DERY-XXXX-XXXX-XXXX-XXXX. */
private object LicenseKeys {
    // Embedded shared secret — fine for a boutique offline POS license
    // scheme; the goal is to deter casual key-sharing, not defeat reverse
    // engineering. Keys are generated by DeryCode when a shop pays.
    private const val SECRET = "DeryAccount-Offline-License-v1-2026-KampalaUG"
    private const val ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"
    private val ymd = SimpleDateFormat("yyyyMMdd", Locale.US)

    fun generate(plan: PlanTier, expiresAtMillis: Long): String {
        val expStr = ymd.format(java.util.Date(expiresAtMillis))
        val payload = plan.code + expStr
        val sig = sign(payload).take(8)
        val raw = payload + sig
        return "DERY-" + raw.chunked(4).joinToString("-")
    }

    /** Returns (plan, expiresAtMillis) if the code is authentic, else null. */
    fun verify(rawInput: String): Pair<PlanTier, Long>? {
        val clean = rawInput.trim().uppercase(Locale.US)
            .removePrefix("DERY-").replace("-", "").replace(" ", "")
        if (clean.length < 18) return null
        val code = clean.substring(0, 2)
        val expStr = clean.substring(2, 10)
        val sig = clean.substring(10, 18)
        val plan = PlanTier.byCode(code) ?: return null
        if (sign(code + expStr).take(8) != sig) return null
        val expiresAt = try {
            ymd.parse(expStr)?.time ?: return null
        } catch (e: Exception) { return null }
        return plan to expiresAt
    }

    private fun sign(payload: String): String {
        val mac = Mac.getInstance("HmacSHA256")
        mac.init(SecretKeySpec(SECRET.toByteArray(), "HmacSHA256"))
        return base32(mac.doFinal(payload.toByteArray()))
    }

    private fun base32(bytes: ByteArray): String {
        val sb = StringBuilder()
        var buffer = 0
        var bitsLeft = 0
        for (b in bytes) {
            buffer = (buffer shl 8) or (b.toInt() and 0xFF)
            bitsLeft += 8
            while (bitsLeft >= 5) {
                bitsLeft -= 5
                sb.append(ALPHABET[(buffer shr bitsLeft) and 0x1F])
            }
        }
        return sb.toString()
    }
}

sealed class ActivationResult {
    data class Success(val plan: PlanTier, val expiresAt: Long) : ActivationResult()
    object InvalidCode : ActivationResult()
    object Expired : ActivationResult()
}

/** Manages trial state + activation code, backed by SharedPreferences (no DB migration needed). */
object LicenseManager {
    private const val PREFS = "dery_license"
    private const val K_TRIAL_START = "trial_start"
    private const val K_PLAN = "plan"
    private const val K_KEY = "key"
    private const val K_EXPIRES = "expires_at"

    const val TRIAL_DAYS = 21

    private fun prefs(context: Context) =
        context.applicationContext.getSharedPreferences(PREFS, Context.MODE_PRIVATE)

    /** Call once at app start — starts the trial clock on first ever launch. */
    fun ensureTrialStarted(context: Context) {
        val p = prefs(context)
        if (!p.contains(K_TRIAL_START)) {
            p.edit().putLong(K_TRIAL_START, System.currentTimeMillis()).apply()
        }
    }

    fun state(context: Context): LicenseState {
        val p = prefs(context)
        val trialStart = p.getLong(K_TRIAL_START, System.currentTimeMillis())
        val trialEnd = trialStart + TRIAL_DAYS * 24L * 60 * 60 * 1000
        val now = System.currentTimeMillis()
        val trialDaysLeft = (((trialEnd - now) / (24L * 60 * 60 * 1000)) + 1).toInt().coerceAtLeast(0)
        val isTrial = now < trialEnd

        val planCode = p.getString(K_PLAN, null)
        val licenseKey = p.getString(K_KEY, null)
        val expiresAt = if (p.contains(K_EXPIRES)) p.getLong(K_EXPIRES, 0L) else null
        val licensedPlan = planCode?.let { PlanTier.byCode(it) }
        val isLicensed = licensedPlan != null && expiresAt != null && now < expiresAt

        val plan = when {
            isLicensed -> licensedPlan!!
            isTrial -> PlanTier.PROFESSIONAL   // show the full system during the trial
            else -> licensedPlan ?: PlanTier.STARTER
        }
        val isExpired = !isTrial && !isLicensed && (licensedPlan != null || trialEnd < now)

        return LicenseState(
            plan = plan, isTrial = isTrial && !isLicensed, trialDaysLeft = trialDaysLeft,
            isLicensed = isLicensed, isExpired = isExpired,
            expiresAt = expiresAt, licenseKey = licenseKey
        )
    }

    /** Verifies and stores an activation code the shop received from DeryCode. */
    fun activate(context: Context, rawCode: String): ActivationResult {
        val parsed = LicenseKeys.verify(rawCode) ?: return ActivationResult.InvalidCode
        val (plan, expiresAt) = parsed
        if (expiresAt < System.currentTimeMillis()) return ActivationResult.Expired
        prefs(context).edit()
            .putString(K_PLAN, plan.code)
            .putString(K_KEY, rawCode.trim().uppercase(Locale.US))
            .putLong(K_EXPIRES, expiresAt)
            .apply()
        return ActivationResult.Success(plan, expiresAt)
    }

    fun clearLicense(context: Context) {
        prefs(context).edit().remove(K_PLAN).remove(K_KEY).remove(K_EXPIRES).apply()
    }

    /** For DeryCode/Wema's own use — generates a real code to send a paying shop. */
    fun generateCodeForSupport(plan: PlanTier, months: Int): String {
        val cal = Calendar.getInstance()
        cal.add(Calendar.MONTH, months)
        return LicenseKeys.generate(plan, cal.timeInMillis)
    }
}
