package com.derycode.deryaccount.catalog

/**
 * BusinessCatalog — predefined item lists per business category so the
 * owner just PICKS items instead of typing them one by one.
 * Prices are typical Ugandan market prices (editable per item).
 * Everything is local — no connection needed.
 */
object BusinessCatalog {

    data class CatalogItem(val name: String, val unit: String, val price: Double)

    val CATEGORIES = listOf(
        "General Shop", "Supermarket", "Hardware", "Pharmacy / Drug Shop",
        "Agro-Vet & Farm", "Butchery", "Salon & Cosmetics", "Stationery / Bookshop",
        "Bar & Restaurant", "Mobile Money & Airtime"
    )

    fun itemsFor(category: String): List<CatalogItem> = when (category) {
        "General Shop" -> listOf(
            CatalogItem("Sugar 1kg", "kg", 5000.0),
            CatalogItem("Sugar 2kg", "pack", 9800.0),
            CatalogItem("Rice 1kg (Kaiso)", "kg", 4500.0),
            CatalogItem("Rice 1kg (Super)", "kg", 6500.0),
            CatalogItem("Posho 1kg", "kg", 3500.0),
            CatalogItem("Cooking Oil 1L", "btl", 8500.0),
            CatalogItem("Cooking Oil 3L", "jerrican", 24000.0),
            CatalogItem("Wheat Flour 1kg", "kg", 5500.0),
            CatalogItem("Salt 500g", "pack", 1000.0),
            CatalogItem("Bread", "loaf", 4500.0),
            CatalogItem("Baking Powder 100g", "tin", 1500.0),
            CatalogItem("Beans 1kg", "kg", 5000.0),
            CatalogItem("Groundnuts 1kg", "kg", 7000.0),
            CatalogItem("Milk 500ml", "pkt", 2000.0),
            CatalogItem("Tea Leaves 100g (Kabojja)", "tin", 3000.0),
            CatalogItem("Coffee 100g", "tin", 3500.0),
            CatalogItem("Cocoa 100g", "tin", 3000.0),
            CatalogItem("Rice 5kg", "pack", 28000.0),
            CatalogItem("Millet Flour 1kg", "kg", 4000.0),
            CatalogItem("Ghee 250g", "tin", 8000.0),
            CatalogItem("Honey 500g", "bottle", 15000.0),
            CatalogItem("Packed Curry Powder 50g", "pack", 1000.0),
            CatalogItem("Spices Mix 50g", "pack", 1500.0),
            CatalogItem("Sweets (Assorted)", "pkt", 500.0),
            CatalogItem("Biscuits (Glucose)", "pkt", 1000.0),
            CatalogItem("Cakes (Snack)", "pc", 1000.0),
            CatalogItem("Eggs (Tray of 30)", "tray", 15000.0)
        )
        "Supermarket" -> listOf(
            CatalogItem("Coca-Cola 300ml", "btl", 1500.0),
            CatalogItem("Pepsi 300ml", "btl", 1500.0),
            CatalogItem("Sprite 300ml", "btl", 1500.0),
            CatalogItem("Fanta 300ml", "btl", 1500.0),
            CatalogItem("Novida 300ml", "btl", 1500.0),
            CatalogItem("Mountain Dew 500ml", "btl", 2000.0),
            CatalogItem("Krest 300ml", "btl", 1500.0),
            CatalogItem("Rwenzori Water 500ml", "btl", 1000.0),
            CatalogItem("Rwenzori Water 1.5L", "btl", 2500.0),
            CatalogItem("Minute Maid 500ml", "pkt", 2000.0),
            CatalogItem("Azure Water 500ml", "btl", 1000.0),
            CatalogItem("Bushera 500ml", "bottle", 2500.0),
            CatalogItem("Milk Shake 250ml", "pkt", 2000.0),
            CatalogItem("Yoghurt 500ml", "cup", 3500.0),
            CatalogItem("Biscuits (Assorted)", "pkt", 1500.0),
            CatalogItem("Chips (Potato Crisps)", "pkt", 1000.0),
            CatalogItem("Chocolates", "pc", 2000.0),
            CatalogItem("Juice Concentrate 1L", "btl", 8000.0),
            CatalogItem("Toilet Paper (2-ply)", "roll", 1500.0),
            CatalogItem("Tissues (Facial)", "pkt", 2000.0),
            CatalogItem("Detergent Omo 500g", "pkt", 4500.0),
            CatalogItem("Bar Soap (Geisha)", "bar", 3000.0),
            CatalogItem("JIK Bleach 500ml", "btl", 3500.0),
            CatalogItem("Toothpaste 100ml", "tube", 3000.0),
            CatalogItem("Toothbrush", "pc", 1500.0),
            CatalogItem("Matchbox (10-pack)", "pkt", 1000.0),
            CatalogItem("Candles (Packet)", "pkt", 2500.0),
            CatalogItem("Batteries AA (2)", "pkt", 1000.0),
            CatalogItem("Razors (Packet)", "pkt", 1500.0),
            CatalogItem("Sanitary Pads", "pkt", 3000.0),
            CatalogItem("Diapers (Small Pack)", "pkt", 12000.0),
            CatalogItem("Baby Wipes", "pkt", 3000.0),
            CatalogItem("Slippers", "pair", 5000.0),
            CatalogItem("Socks (Pair)", "pair", 2000.0)
        )
        "Hardware" -> listOf(
            CatalogItem("Cement 50kg (Tororo)", "bag", 34000.0),
            CatalogItem("Cement 50kg (Hima)", "bag", 35000.0),
            CatalogItem("Iron Sheets 30G (each)", "pc", 45000.0),
            CatalogItem("Iron Sheets 32G (each)", "pc", 38000.0),
            CatalogItem("Round Bars 12mm (length)", "pc", 15000.0),
            CatalogItem("Steel Wire Mesh", "roll", 25000.0),
            CatalogItem("Nails 2-inch (kg)", "kg", 8000.0),
            CatalogItem("Nails 3-inch (kg)", "kg", 8000.0),
            CatalogItem("Nails 4-inch (kg)", "kg", 8000.0),
            CatalogItem("Roofing Nails (kg)", "kg", 10000.0),
            CatalogItem("Bricks (Fired)", "pc", 500.0),
            CatalogItem("Sand (Truck)", "trip", 250000.0),
            CatalogItem("Hardcore (Truck)", "trip", 180000.0),
            CatalogItem("Doors (Ordinary)", "pc", 120000.0),
            CatalogItem("Door Locks", "pc", 15000.0),
            CatalogItem("Hinges (Pair)", "pair", 3000.0),
            CatalogItem("Paint 20L (Crown)", "tin", 90000.0),
            CatalogItem("Paint 4L (Crown)", "tin", 22000.0),
            CatalogItem("Paint Brush 3-inch", "pc", 8000.0),
            CatalogItem("Lacquer 4L", "tin", 25000.0),
            CatalogItem("Primer 20L", "tin", 60000.0),
            CatalogItem("PVC Pipes 4-inch (3m)", "pc", 15000.0),
            CatalogItem("PVC Pipes 2-inch (3m)", "pc", 8000.0),
            CatalogItem("Elbow Joints 4-inch", "pc", 3000.0),
            CatalogItem("Taps (Basin)", "pc", 12000.0),
            CatalogItem("Water Tank 1000L", "pc", 350000.0),
            CatalogItem("Electric Cable 1.5mm (roll)", "roll", 95000.0),
            CatalogItem("Switches (Sockets)", "pc", 5000.0),
            CatalogItem("Bulbs LED (9W)", "pc", 8000.0),
            CatalogItem("Padlocks (Large)", "pc", 10000.0),
            CatalogItem("Hoes (Flat)", "pc", 15000.0),
            CatalogItem("Pangas", "pc", 12000.0),
            CatalogItem("Crowbar", "pc", 20000.0),
            CatalogItem("Wheelbarrow", "pc", 120000.0),
            CatalogItem("Spades", "pc", 25000.0),
            CatalogItem("Hammers", "pc", 15000.0),
            CatalogItem("Measuring Tape 5m", "pc", 8000.0)
        )
        "Pharmacy / Drug Shop" -> listOf(
            CatalogItem("Panadol (Strip)", "strip", 2000.0),
            CatalogItem("Panadol Extra (Strip)", "strip", 2500.0),
            CatalogItem("Coartem (Pack)", "pack", 5000.0),
            CatalogItem("Amoxicillin (Caps)", "pack", 3000.0),
            CatalogItem("ORS Sachets (Pack)", "pack", 2000.0),
            CatalogItem("Zinc Tablets (Pack)", "pack", 2500.0),
            CatalogItem("Cough Syrup 100ml", "btl", 6000.0),
            CatalogItem("Chlorpheniramine (Strip)", "strip", 1500.0),
            CatalogItem("Ibuprofen (Strip)", "strip", 1500.0),
            CatalogItem("Aspirin (Strip)", "strip", 1000.0),
            CatalogItem("Antacid (Bottle)", "btl", 5000.0),
            CatalogItem("Metronidazole (Strip)", "strip", 1500.0),
            CatalogItem("Ciprofloxacin (Strip)", "strip", 2500.0),
            CatalogItem("Paracetamol Syrup 60ml", "btl", 4000.0),
            CatalogItem("Cotton Wool 100g", "roll", 2000.0),
            CatalogItem("Bandages (Roll)", "roll", 2000.0),
            CatalogItem("Plasters (Roll)", "roll", 1500.0),
            CatalogItem("Surgical Spirit 250ml", "btl", 3000.0),
            CatalogItem("Surgical Gloves (Pair)", "pair", 1000.0),
            CatalogItem("Syringes 5ml", "pc", 500.0),
            CatalogItem("Needles (Packet)", "pkt", 2000.0),
            CatalogItem("Condoms (Packet)", "pkt", 2000.0),
            CatalogItem("Malaria Test Kits (RDT)", "pc", 2000.0),
            CatalogItem("Pregnancy Test Kit", "pc", 3000.0),
            CatalogItem("Betadine Solution 100ml", "btl", 5000.0),
            CatalogItem("Eye Drops", "btl", 5000.0),
            CatalogItem("Antiseptic Soap", "bar", 3000.0),
            CatalogItem("Multivitamin Tablets (Pack)", "pack", 5000.0),
            CatalogItem("Iron Supplements (Pack)", "pack", 4000.0),
            CatalogItem("Vitamin C (Pack)", "pack", 3000.0)
        )
        "Agro-Vet & Farm" -> listOf(
            CatalogItem("Maize Seeds 1kg (Longe)", "kg", 6000.0),
            CatalogItem("Bean Seeds 1kg", "kg", 8000.0),
            CatalogItem("DAP Fertilizer 50kg", "bag", 180000.0),
            CatalogItem("NPK 50kg", "bag", 190000.0),
            CatalogItem("Urea 50kg", "bag", 170000.0),
            CatalogItem("Manure (Bag)", "bag", 10000.0),
            CatalogItem("Sprayers (16L)", "pc", 120000.0),
            CatalogItem("Dudu Acelle 100ml", "btl", 15000.0),
            CatalogItem("Rocket 100ml", "btl", 12000.0),
            CatalogItem("Weed Master 100ml", "btl", 10000.0),
            CatalogItem("Cattle Dip 1L", "btl", 25000.0),
            CatalogItem("Chicken Feed 50kg (Layers)", "bag", 130000.0),
            CatalogItem("Chicken Feed 50kg (Chicks)", "bag", 140000.0),
            CatalogItem("Poultry Vaccines", "vial", 10000.0),
            CatalogItem("Day-Old Chicks", "pc", 3500.0),
            CatalogItem("Egg Trays", "tray", 500.0),
            CatalogItem("Drinking Troughs", "pc", 15000.0),
            CatalogItem("Poultry Feeders", "pc", 12000.0),
            CatalogItem("Rabbit Cages", "pc", 50000.0),
            CatalogItem("Grafting Tools", "set", 10000.0)
        )
        "Butchery" -> listOf(
            CatalogItem("Beef (kg)", "kg", 16000.0),
            CatalogItem("Goat Meat (kg)", "kg", 18000.0),
            CatalogItem("Pork (kg)", "kg", 15000.0),
            CatalogItem("Chicken Whole (kg)", "kg", 14000.0),
            CatalogItem("Liver (kg)", "kg", 10000.0),
            CatalogItem("Tripe (kg)", "kg", 8000.0),
            CatalogItem("Ox Tail (kg)", "kg", 12000.0),
            CatalogItem("Sausages (kg)", "kg", 18000.0),
            CatalogItem("Minced Meat (kg)", "kg", 17000.0),
            CatalogItem("Smoked Meat (kg)", "kg", 20000.0)
        )
        "Salon & Cosmetics" -> listOf(
            CatalogItem("Hair Relaxer 500ml", "tin", 15000.0),
            CatalogItem("Shampoo 500ml", "btl", 12000.0),
            CatalogItem("Conditioner 500ml", "btl", 12000.0),
            CatalogItem("Hair Food 250g", "tin", 8000.0),
            CatalogItem("Petroleum Jelly 250g", "tin", 4000.0),
            CatalogItem("Coconut Oil 250ml", "btl", 10000.0),
            CatalogItem("Body Lotion 500ml", "btl", 10000.0),
            CatalogItem("Body Soap (Bar)", "bar", 3000.0),
            CatalogItem("Perfume Spray", "pc", 15000.0),
            CatalogItem("Lipstick", "pc", 5000.0),
            CatalogItem("Foundation 30ml", "btl", 12000.0),
            CatalogItem("Nail Polish", "pc", 3000.0),
            CatalogItem("Weaves (Weave)", "pc", 25000.0),
            CatalogItem("Braids (Pack)", "pkt", 15000.0),
            CatalogItem("Combs", "pc", 2000.0),
            CatalogItem("Hair Brushes", "pc", 5000.0),
            CatalogItem("Hair Dryers", "pc", 80000.0),
            CatalogItem("Curling Irons", "pc", 60000.0),
            CatalogItem("Razor Blades (Packet)", "pkt", 1500.0),
            CatalogItem("Shaving Cream", "btl", 5000.0)
        )
        "Stationery / Bookshop" -> listOf(
            CatalogItem("Exercise Books 32pg", "pc", 1000.0),
            CatalogItem("Exercise Books 48pg", "pc", 1500.0),
            CatalogItem("Exercise Books 64pg", "pc", 2000.0),
            CatalogItem("Pens (Blue Bic)", "pc", 500.0),
            CatalogItem("Pens (Red Bic)", "pc", 500.0),
            CatalogItem("Pencils HB", "pc", 500.0),
            CatalogItem("Rulers 30cm", "pc", 1000.0),
            CatalogItem("Erasers", "pc", 500.0),
            CatalogItem("Sharpeners", "pc", 500.0),
            CatalogItem("Crayons (12-pack)", "pkt", 3000.0),
            CatalogItem("Colored Pencils", "pkt", 4000.0),
            CatalogItem("Markers (Whiteboard)", "pc", 2000.0),
            CatalogItem("Highlighters", "pc", 2000.0),
            CatalogItem("Geometry Sets", "set", 3000.0),
            CatalogItem("Calculators (Basic)", "pc", 15000.0),
            CatalogItem("A4 Paper (Ream)", "ream", 25000.0),
            CatalogItem("Files (Folders)", "pc", 2000.0),
            CatalogItem("Envelopes A4", "pkt", 3000.0),
            CatalogItem("Staplers", "pc", 8000.0),
            CatalogItem("Staple Pins", "pkt", 1500.0),
            CatalogItem("Glue Sticks", "pc", 2000.0),
            CatalogItem("Tape (Roll)", "roll", 1500.0),
            CatalogItem("School Bags", "pc", 30000.0)
        )
        "Bar & Restaurant" -> listOf(
            CatalogItem("Beer (Nile Special)", "btl", 6000.0),
            CatalogItem("Beer (Club)", "btl", 5000.0),
            CatalogItem("Beer (Bell)", "btl", 5000.0),
            CatalogItem("Beer (Guinness)", "btl", 5500.0),
            CatalogItem("Beer (Tusker Malt)", "btl", 5500.0),
            CatalogItem("Waragi 350ml", "btl", 5000.0),
            CatalogItem("Waragi 750ml", "btl", 15000.0),
            CatalogItem("Konyagi 350ml", "btl", 5000.0),
            CatalogItem("Bond 7 750ml", "btl", 25000.0),
            CatalogItem("Wine 750ml", "btl", 20000.0),
            CatalogItem("Soda 500ml", "btl", 2500.0),
            CatalogItem("Juice 500ml", "pkt", 2000.0),
            CatalogItem("Rice Plate (Dish)", "plate", 5000.0),
            CatalogItem("Posho & Beans (Dish)", "plate", 4000.0),
            CatalogItem("Chips (Dish)", "plate", 7000.0),
            CatalogItem("Rolex", "pc", 3000.0),
            CatalogItem("Roast Chicken (Dish)", "plate", 12000.0),
            CatalogItem("Beef Stew (Dish)", "plate", 8000.0),
            CatalogItem("Fish (Dish)", "plate", 15000.0),
            CatalogItem("Matoke (Dish)", "plate", 5000.0),
            CatalogItem("Groundnut Sauce (Dish)", "plate", 5000.0),
            CatalogItem("Chapati", "pc", 1000.0),
            CatalogItem("Tea (Cup)", "cup", 1000.0),
            CatalogItem("Coffee (Cup)", "cup", 2000.0),
            CatalogItem("Water 500ml", "btl", 1000.0)
        )
        "Mobile Money & Airtime" -> listOf(
            CatalogItem("Airtime (Assorted)", "pc", 500.0),
            CatalogItem("MTN Airtime 500", "pc", 500.0),
            CatalogItem("MTN Airtime 1000", "pc", 1000.0),
            CatalogItem("MTN Airtime 2000", "pc", 2000.0),
            CatalogItem("MTN Airtime 5000", "pc", 5000.0),
            CatalogItem("Airtel Airtime 500", "pc", 500.0),
            CatalogItem("Airtel Airtime 1000", "pc", 1000.0),
            CatalogItem("Airtel Airtime 2000", "pc", 2000.0),
            CatalogItem("Airtel Airtime 5000", "pc", 5000.0),
            CatalogItem("Data Bundles (7GB)", "pc", 10000.0),
            CatalogItem("Data Bundles (1.5GB)", "pc", 3000.0),
            CatalogItem("WhatsApp Bundles (Daily)", "pc", 500.0),
            CatalogItem("SIM Cards (MTN)", "pc", 2000.0),
            CatalogItem("SIM Cards (Airtel)", "pc", 2000.0),
            CatalogItem("SIM Registration Fees", "pc", 1000.0),
            CatalogItem("MoMo Withdrawal Fees", "pc", 500.0),
            CatalogItem("Phone Chargers", "pc", 8000.0),
            CatalogItem("Earphones", "pc", 5000.0),
            CatalogItem("Phone Covers", "pc", 3000.0),
            CatalogItem("Screen Protectors", "pc", 2000.0)
        )
        else -> emptyList()
    }
}
